name: ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Build Go application
      - name: Build Go application
        run: go build -o hello-world .

      # Step 5: Run the Go application in the background
      - name: Run Hello World application
        run: |
          nohup ./hello-world &
          sleep 5 # wait a moment for the server to start

      # Step 6: Run ZAP Full Scan and Generate Report
      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "https://demo-cr-812511643824.europe-west1.run.app"
          cmd_options: "-config api.disablekey=true -report /tmp/zap-report.html"

      # Step 7: Upload ZAP Scan Report as an Artifact
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: /tmp/zap-report.html
