name: "ZAP Scan - Public endpoint DAST Testing"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TARGET_URL: "https://eod-ml3.appsdemo.se/"
  RETENTION_DAYS: 7

jobs:
  zap_scan:
    name: Perform DAST scanning of external application endpoint
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Create a Writable Directory for ZAP
      - name: Prepare Work Directory
        run: |
          mkdir -p zap-workdir
          sudo chown 1001:1001 zap-workdir
          chmod 775 zap-workdir

      # 3. Run ZAP Baseline Scan (allow step to continue on failure)
      - name: Run DAST Scan
        continue-on-error: true
        run: |
          docker run --rm \
          -v $(pwd)/zap-workdir:/zap/wrk \
          -t ghcr.io/zaproxy/zaproxy zap-baseline.py \
          -t ${{ env.TARGET_URL }} \
          -r zap_report.html || echo "ZAP Baseline Scan encountered issues, check the logs."

      # 4. Upload ZAP Scan Report as Artifact
      - name: Upload DAST Scan Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Dast_Scan_Report
          path: zap-workdir/zap_report.html
          retention-days: ${{ env.RETENTION_DAYS }}
      
      # 5. Analyze ZAP Scan Report and Notify Teams
      #- name: Notify Microsoft Teams on Vulnerability Detection
      #  if: always()  # Runs regardless of previous step's success
      #  run: |
      #    if grep -q "FAIL-NEW" zap-workdir/zap_report.html; then
      #      curl -H 'Content-Type: application/json' -d '{
      #        "title": "ZAP Scan Vulnerability Detected",
      #        "text": "Vulnerabilities have been detected during the ZAP scan. Please review the report."
      #      }' "${{ env.TEAMS_WEBHOOK_URL }}"
      #    else
      #      echo "No vulnerabilities detected. Teams notification not sent."    