name: "ZAP Scan for DAST Testing"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    name: Run OWASP ZAP Scan
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Create a Writable Directory for ZAP
      - name: Prepare Work Directory
        run: |
          mkdir -p zap-workdir
          chmod 777 zap-workdir

      # 3. Run ZAP Baseline Scan (allow step to continue on failure)
      - name: Run ZAP Baseline Scan
        continue-on-error: true  # Allow the job to continue even if this step fails
        run: |
          docker run --rm \
          -v $(pwd)/zap-workdir:/zap/wrk \
          -t ghcr.io/zaproxy/zaproxy zap-baseline.py \
          -t https://hello-812511643824.europe-west1.run.app \
          -r zap_report.html || true

      # 4. Upload ZAP Scan Report as Artifact (runs regardless of scan result)
      - name: Upload ZAP Scan Report
        if: always()  # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: ZAP_Scan_Report
          path: zap-workdir/zap_report.html
          retention-days: 7
