name: "ZAP Scan & CodeQL Security Analysis"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TARGET_URL: "https://hello-812511643824.europe-west1.run.app"
  RETENTION_DAYS: 7

jobs:
  zap_scan:
    name: Perform DAST scanning of external application endpoint
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Create a Writable Directory for ZAP
      - name: Prepare Work Directory
        run: |
          mkdir -p zap-workdir
          chmod 777 zap-workdir

      # 3. Run ZAP Baseline Scan (allow step to continue on failure)
      - name: Run DAST Scan
        continue-on-error: true
        timeout-minutes: 30
        run: |
          echo "Running ZAP scan on ${{ env.TARGET_URL }}"
          docker run --rm \
          -v $(pwd)/zap-workdir:/zap/wrk \
          -t ghcr.io/zaproxy/zaproxy zap-full-scan.py \
          -t ${{ env.TARGET_URL }} \
          -r zap_report.html || echo "ZAP scan failed, but continuing workflow."

      # 4. Debugging: List Files in zap-workdir
      - name: Debug - List Files in zap-workdir
        if: always()
        run: |
          echo "Files in zap-workdir:"
          ls -la zap-workdir

      # 5. Upload ZAP Scan Reports as Artifact (runs regardless of scan result)
      - name: Upload DAST Scan Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Dast_Scan_Reports
          path: zap-workdir/
          retention-days: ${{ env.RETENTION_DAYS }}