name: ZAP API Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-api-scan:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Test API Reachability
      - name: Test API Reachability
        run: curl -I https://demo-cr-812511643824.europe-west1.run.app

      # Step 3: Run ZAP API Scan
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          target: "https://demo-cr-812511643824.europe-west1.run.app"
          cmd_options: "-d -J /zap/wrk/zap-report.json -w /zap/wrk/zap-report.md -r /zap/wrk/zap-report.html"
        continue-on-error: true

      # Step 4: Debug Output Directory
      - name: Debug Output Directory
        if: always()
        run: ls -l /home/runner/work/gh-advanced-test/gh-advanced-test

      # Step 5: Upload ZAP Reports
      - name: Upload ZAP Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: /home/runner/work/gh-advanced-test/gh-advanced-test/zap-report.*
