name: ZAP API Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-api-scan:
    runs-on: ubuntu-22.04  # Specify the version to avoid changes in ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run ZAP API Scan
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          target: "https://demo-cr-812511643824.europe-west1.run.app"
          cmd_options: "-J /zap/wrk/zap-report.json -w /zap/wrk/zap-report.md -r /zap/wrk/zap-report.html"

      # Step 3: Debug ZAP Output Directory
      - name: Debug Output Directory
        run: ls -l /home/runner/work/gh-advanced-test/gh-advanced-test

      # Step 4: Upload ZAP Reports
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: /home/runner/work/gh-advanced-test/gh-advanced-test/zap-report.*
