name: ZAP API Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-api-scan:
    runs-on: ubuntu-24.04  # Specify version to avoid ubuntu-latest changes

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run ZAP API Scan
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          target: "https://demo-cr-812511643824.europe-west1.run.app"
          cmd_options: "-config api.disablekey=true -J /tmp/zap-report.json -w /tmp/zap-report.md -r /tmp/zap-report.html"

      # Step 3: Debug Output Directory
      - name: Debug Output Directory
        run: ls -l /tmp

      # Step 4: Upload ZAP Reports
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: /tmp/zap-report.*
